added cache and report

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Compile the bot and build the docker image
+name: Test api and build the docker image
 
 on:
   push:
@@ -20,15 +20,20 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.12'
-
+          cache: 'pip'
+          cache-dependency-path: './requirements.dev.txt'
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.dev.txt
-
       - name: Run tests
         run: |
           python -m pytest ./tests -v --disable-warnings --doctest-modules --junitxml=junit/test-results.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'junit/test-results.xml'
 
   build-docker-image:
     runs-on: ubuntu-latest
